import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { withSSRPrivate } from '../shared/hoc/withSSRPrivate';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import MainLayout from '../layout';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <main></main>
      </MainLayout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = withSSRPrivate(
  async (ctx) => {
    return {
      props: {
        //@ts-ignore
        ...(await serverSideTranslations(ctx.locale, ['common'])),
        token: ctx.req?.cookies?.token,
      },
    };
  },
);

export default Home;
